[package]
name = "adapter"
version = "0.1.0"
edition = "2021"
description = "GoF: Adapter pattern in Rust"
authors = ["GoF Examples <gof@example.com>"]
license = "MIT"

[dependencies]
anyhow.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
